### ISSUE TITLE
flatpak runtime end of life message

### ISSUE THREAD

**Issue by dln949** [flozz/calcleaner#13]
Keep getting this flapak error message, are there plans to update the runtime used by calcleaner?  

Info: org.gnome.Platform//43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.flozz.calcleaner

**Comment by flozz** [comment]
The package on Flathub now use an up to date sdk :)
